name: Coverage
on: push

jobs:
  Codecov:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run codecov
      - name: Codecov
        uses: codecov/codecov-action@v1
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2