name: Coverage
on: push

jobs:
  Codecov:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run coverage
      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage/lcov.info