name: Coverage
on: push

jobs:
  Codecove:
    name: Codecove
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run codecove
      - uses: codecov/codecov-action@v1